language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t babitabisht/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run babitabisht/client-test npm  run test -- --coverage

after_success:
  - docker build -t babitabisht/multi-client ./client
  - docker build -t babitabisht/multi-nginx  ./nginx
  - docker build -t babitabisht/multi-server ./server
  - docker build -t babitabisht/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push  babitabisht/multi-client
  - docker push  babitabisht/multi-nginx
  - docker push  babitabisht/multi-server
  - docker push  babitabisht/multi-worker

deploy:
  provider: elasticbeanstalk
  region : us-east-1
  app : multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-844579967235
  bucket_path : docker-multi
  on:
    branch : master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY